<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'PizzaConsole\Controller\IndexController'        => __DIR__ . '/src/PizzaConsole/Controller/IndexController.php',
  'PizzaConsole\Controller\IndexControllerFactory' => __DIR__ . '/src/PizzaConsole/Controller/IndexControllerFactory.php',
  'PizzaConsole\Module'                            => __DIR__ . '/Module.php',
);
