<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'PizzaGenerator\Controller\IndexController'        => __DIR__ . '/src/PizzaGenerator/Controller/IndexController.php',
  'PizzaGenerator\Controller\IndexControllerFactory' => __DIR__ . '/src/PizzaGenerator/Controller/IndexControllerFactory.php',
  'PizzaGenerator\Module'                            => __DIR__ . '/Module.php',
);
