<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'PizzaData\Table\PizzaTable'              => __DIR__ . '/src/PizzaData/Table/PizzaTable.php',
  'PizzaData\Table\PizzaTableFactory'       => __DIR__ . '/src/PizzaData/Table/PizzaTableFactory.php',
  'PizzaData\Table\PizzaTableInterface'     => __DIR__ . '/src/PizzaData/Table/PizzaTableInterface.php',
  'PizzaData\Service\PizzaServiceInterface' => __DIR__ . '/src/PizzaData/Service/PizzaServiceInterface.php',
  'PizzaData\Service\PizzaServiceFactory'   => __DIR__ . '/src/PizzaData/Service/PizzaServiceFactory.php',
  'PizzaData\Service\PizzaService'          => __DIR__ . '/src/PizzaData/Service/PizzaService.php',
  'PizzaData\Module'                        => __DIR__ . '/Module.php',
);
