<?php
/**
 * Zend Framework 2 - PHP-Magazin Konsole und ZF2
 *
 * Beispiele für ZF2 Konsolenanwendungen
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * namespace definition and usage
 */

/**
 * Index view script
 *
 * @package    Application
 */

$this->headTitle('Herzlich Willkommen!');

?>
<div class="jumbotron">
    <h1>Zend Framework 2 - PHP-Magazin Konsole und ZF2</h1>
    <p>
        In diesem Projekt finden Sie die lauffähigen Beispiele für den Artikel
        zum Zend Framework 2 Konsolenanwendungen aus dem PHP Magazin.
    </p>
</div>
<h2>Pizza Daten</h2>
<table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
    <tr>
        <th>ID</th>
        <th>Titel</th>
        <th>Bezeichnung</th>
        <th>Preis</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->pizzaList as $pizzaRow): ?>
        <tr>
            <td><?php echo $pizzaRow['id']; ?></td>
            <td><?php echo $pizzaRow['title']; ?></td>
            <td><?php echo $pizzaRow['description']; ?></td>
            <td><?php echo $this->currencyFormat($pizzaRow['price'] / 100, 'EUR'); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

